services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    restart: unless-stopped
    env_file: ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./omada/data:/opt/tplink/efs/data
      - ./omada/logs:/opt/tplink/efs/logs
    network_mode: host
