services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    env_file: ../.env

    ports:
      - '80:80'   # Standard web traffic
      - '81:81'   # The Management Dashboard
      - '443:443' # Secure (SSL) traffic

    environment:
      TZ: ${TZ}
      INITIAL_ADMIN_EMAIL: ${PROXY_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${PROXY_PASSWD}


    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
