title: Tps homelab
theme: dark
color: slate
background: /images/background.png
backgroundOpacity: 0.83


cardBlur: xl
language: pt

disableCollapse: true
useEqualHeights: true

showStats: true

fullWidth: true

fadeIn: true

favicon: /icons/amp.webp

target: _blank


layout:
  - Geral:
      header: false
      style: row
      columns: 5
  - Monitoramento:
      header: false
      style: row
      columns: 3
  - Note:
      icon: /icons/bars.svg
      header: true
      style: row
      columns: 2
  - Links:
      icon: /icons/link.svg
      header: true
      style: row
      columns: 3
