title: Tps homelab
theme: dark
color: slate
background: /images/bg2.jpg
backgroundOpacity: 0.83

cardBlur: xs

disableCollapse: true
useEqualHeights: true

showStats: true
fullWidth: true
fadeIn: true
favicon: /images/amp.webp
target: _blank


layout:
  # Monitoramento:
  #   style: row
  #   columns: 3
  # Media:
  #   icon: /icons/icon_video.png
  #   style: row
  #   columns: 3
  # Downloaders:
  #   icon: /icons/icon_download.png
  Network:
    icon: /icons/icon_network.png
  Applications:
    icon: /icons/icon_apps.png
  Proxmox Status:
    icon: /icons/icon_server.png
    style: row
    columns: 5
